name: Test Flakiness on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-flakiness:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run all tests 100 times to check for flakiness
      run: |
        echo "Running ALL tests 100 times on Windows to verify stability..."
        $FAILED = 0
        for ($i = 1; $i -le 100; $i++) {
          if ($i % 10 -eq 0) {
            Write-Host "Progress: $i/100 runs completed"
          }
          $result = go test ./... -timeout=60s 2>&1
          if ($LASTEXITCODE -ne 0) {
            Write-Host "❌ FAILURE at run $i"
            Write-Host "Re-running with verbose output to show failure:"
            go test ./... -v -timeout=60s
            $FAILED++
            if ($FAILED -gt 3) {
              Write-Host "Too many failures ($FAILED), stopping early"
              exit 1
            }
          }
        }
        Write-Host "✅ Completed 100 runs with $FAILED failures"
        if ($FAILED -eq 0) {
          Write-Host "🎉 No flakiness detected in any tests!"
        } else {
          Write-Host "⚠️ Found $FAILED flaky test runs"
          exit 1
        }