name: Test Flakiness on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-flakiness:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run tests 100 times to check for flakiness
      run: |
        echo "Running tests 100 times on macOS to verify stability..."
        FAILED=0
        for i in {1..100}; do
          echo "Run $i/100"
          if ! go test ./cmd/outfitpicker ./cmd/outfitpicker-admin -timeout=30s; then
            echo "❌ FAILURE at run $i"
            FAILED=$((FAILED + 1))
            if [ $FAILED -gt 5 ]; then
              echo "Too many failures, stopping"
              exit 1
            fi
          fi
        done
        echo "✅ Completed 100 runs with $FAILED failures"
        if [ $FAILED -eq 0 ]; then
          echo "🎉 No flakiness detected!"
        fi