name: Test Flakiness on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-flakiness:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run all tests 100 times to check for flakiness
      run: |
        echo "Running ALL tests 100 times on macOS to verify stability..."
        FAILED=0
        for i in {1..100}; do
          if [ $((i % 10)) -eq 0 ]; then
            echo "Progress: $i/100 runs completed"
          fi
          if ! go test ./... -timeout=60s > /dev/null 2>&1; then
            echo "❌ FAILURE at run $i"
            echo "Re-running with verbose output to show failure:"
            go test ./... -v -timeout=60s
            FAILED=$((FAILED + 1))
            if [ $FAILED -gt 3 ]; then
              echo "Too many failures ($FAILED), stopping early"
              exit 1
            fi
          fi
        done
        echo "✅ Completed 100 runs with $FAILED failures"
        if [ $FAILED -eq 0 ]; then
          echo "🎉 No flakiness detected in any tests!"
        else
          echo "⚠️  Found $FAILED flaky test runs"
          exit 1
        fi